# Generated by Django 3.2.7 on 2021-11-22 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('company_name', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('current_price', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('enterprise_value', models.FloatField()),
                ('forward_pe', models.FloatField()),
                ('enterprise_to_rev', models.FloatField()),
                ('enterprise_to_ebitda', models.FloatField()),
                ('profit_margins', models.FloatField()),
                ('roe', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RelativeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('stocks', models.ManyToManyField(blank=True, related_name='relative_tables', to='relative_table_api.Stock')),
            ],
        ),
    ]
